spring.application.name=ProductGuardian
spring.datasource.url=jdbc:postgresql://localhost:5436/productguardian_db
spring.datasource.username=productguardian
spring.datasource.password=productguardian123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.key=dW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRldW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9lX2ZvcnRl