spring.application.name=product-guardian
spring.datasource.url=jdbc:postgresql://localhost:5436/productguardian_db
spring.datasource.username=productguardian
spring.datasource.password=productguardian123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
